// Generated by https://quicktype.io

class Peliculas {
  List<Pelicula> items = new List();

  Peliculas();

  Peliculas.fromJsonList(List<dynamic> jsonList) {
    if(jsonList == null) return;

    for(var item in jsonList) {
      final pelicula = new Pelicula.fromJsonMap(item);
      items.add(pelicula);
    }
  }
}

class Pelicula {
  String uniqueId;

  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  bool adult;
  String backdropPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;

  Pelicula({
    this.popularity,
    this.voteCount,
    this.video,
    this.posterPath,
    this.id,
    this.adult,
    this.backdropPath,
    this.originalLanguage,
    this.originalTitle,
    this.genreIds,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> json) {
    popularity       = json['popularity'] / 1;
    voteCount        = json['voteCount'];
    video            = json['video'];
    posterPath       = json['posterPath'];
    id               = json['id'];
    adult            = json['adult'];
    backdropPath     = json['backdropPath'];
    originalLanguage = json['originalLanguage'];
    originalTitle    = json['originalTitle'];
    genreIds         = json['genreIds'].cast<int>();
    title            = json['title'];
    voteAverage      = json['voteAverage'] / 1;
    overview         = json['overview'];
    releaseDate      = json['releaseDate'];
  }

  getPosterImg() {
    if(posterPath == null){
      return 'https://sisterhoodofstyle.com/wp-content/uploads/2018/02/no-image-1.jpg';
    } else {
      return 'https://image.tmdb.or/t/p/w500/$posterPath';
    }
  }
  getBackgroundImg() {
    if(posterPath == null){
      return 'https://sisterhoodofstyle.com/wp-content/uploads/2018/02/no-image-1.jpg';
    } else {
      return 'https://image.tmdb.or/t/p/w500/$backdropPath';
    }
  }
}
